//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_Order { get; set; }
        public int Order_number { get; set; }
        public int idUser { get; set; }
        public System.DateTime Order_data { get; set; }
        public Nullable<int> idProduct { get; set; }
        public int Count_Order { get; set; }
        public int idGive { get; set; }
        public string Cost_Order { get; set; }
    
        public virtual Give Give { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
