//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_Product { get; set; }
        public string Product_name { get; set; }
        public string Description_Product { get; set; }
        public int idManufacturer { get; set; }
        public decimal Cost_Product { get; set; }
        public string Img_Product { get; set; }
        public string Category_Product { get; set; }
        public string Unit_Product { get; set; }
        public int Count_Product { get; set; }
        public int idSupplier { get; set; }
        public string Additional_Product { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
